####################################################################
# CAUTION: there is another whitelist on top of this one defined in
# the Sophos Firewall !
###################################################################
x-allowed-ips: &allowed-ips
  - 172.18.0.1/16 # Docker default bridge network
  - 192.168.121.0/24 # local network
  - 10.0.0.0/8 # local network
  - 81.27.115.118/32 # company IP
  - 80.151.133.22/32 # company IP
  - 91.98.165.27/32 # gitea arm64 runner
  - 91.98.139.60/32 # webserver automation-base.com
  - 178.156.129.159/32 # webserver plc-mall.com
  - 157.90.172.118/32 # webserver sps-markt.de
  - 91.99.195.148/32 # webserver plc-index.de
  - 116.203.235.30/32 # webserver automation-base.com NEW

http:
  middlewares:
    gitea-ipwhitelist:
      ipWhiteList:
        sourceRange: *allowed-ips

tcp:
  middlewares:
    gitea-tcp-ipwhitelist:
      ipWhiteList:
        sourceRange: *allowed-ips

log:
  level: DEBUG

accessLog: {} # enables access log with defaults (stdout)
